name: demoQA

on: [push]

jobs:
  demoQA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - uses: Xotabu4/selenoid-github-action@v2

      # Создание GitHub Deployment
      - name: Create GitHub Deployment
        id: create_deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEPLOY_RESPONSE=$(curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{"ref":"main","required_contexts":[],"auto_merge":false,"environment":"production","description":"Deployment from demoQA workflow"}')
          echo "::set-output name=deployment_id::$(echo "$DEPLOY_RESPONSE" | jq -r '.id')"

      # запуск тестов
      - run: chmod +x ./gradlew
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      # скачиваем историю
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # генерируем отчет
      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      # публикуем отчет
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      # Обновляем статус деплоя на success при успешном выполнении всех шагов до этого
      - name: Update Deployment Status - success
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/deployments/${{ steps.create_deployment.outputs.deployment_id }}/statuses \
            -d '{"state": "success"}'

      # Обновляем статус деплоя на failure, если что-то пошло не так
      - name: Update Deployment Status - failure
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/deployments/${{ steps.create_deployment.outputs.deployment_id }}/statuses \
            -d '{"state": "failure"}'
